import React from 'react';
import { FileText, CheckCircle, Mail, X } from 'lucide-react';

export default function PostCallSummaryModal({ isOpen, summaryData, onClose }) {
  if (!isOpen || !summaryData) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm animate-in fade-in duration-200">
      <div className="bg-[#0A0E1A] border border-[#00E5C7]/30 rounded-2xl p-6 max-w-2xl w-full shadow-2xl shadow-[#00E5C7]/20 relative max-h-[90vh] overflow-y-auto">
        <button onClick={onClose} className="absolute top-4 right-4 text-slate-400 hover:text-white">
          <X className="w-5 h-5" />
        </button>

        <div className="flex items-center gap-3 mb-6">
          <div className="w-10 h-10 rounded-full bg-blue-500/20 flex items-center justify-center text-blue-400">
            <FileText className="w-5 h-5" />
          </div>
          <div>
            <h2 className="text-xl font-bold text-white">Call Summary</h2>
            <p className="text-xs text-slate-400">Generated by AI Summary Agent</p>
          </div>
        </div>

        <div className="space-y-6">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="bg-slate-900/50 rounded-xl p-4 border border-slate-700">
              <h3 className="text-sm font-semibold text-slate-300 mb-2">Summary (English)</h3>
              <p className="text-sm text-slate-100 whitespace-pre-wrap">{summaryData.summary_text_a_lang}</p>
            </div>
            <div className="bg-slate-900/50 rounded-xl p-4 border border-slate-700">
              <h3 className="text-sm font-semibold text-slate-300 mb-2">Summary (Translated)</h3>
              <p className="text-sm text-slate-100 whitespace-pre-wrap">{summaryData.summary_text_b_lang}</p>
            </div>
          </div>

          <div className="bg-indigo-900/20 rounded-xl p-4 border border-indigo-500/30">
            <h3 className="text-sm font-semibold text-indigo-300 mb-3 flex items-center gap-2">
              <CheckCircle className="w-4 h-4" /> Action Items
            </h3>
            <ul className="space-y-2">
              {summaryData.action_items.map((item, idx) => (
                <li key={idx} className="text-sm text-indigo-100 flex items-start gap-2">
                  <span className="w-1.5 h-1.5 rounded-full bg-indigo-500 mt-1.5 shrink-0"></span>
                  {item}
                </li>
              ))}
            </ul>
          </div>
        </div>

        <div className="mt-6 flex justify-end gap-3">
          <button 
            className="px-4 py-2 bg-slate-800 hover:bg-slate-700 text-white rounded-xl transition-all font-medium text-sm"
          >
            Copy Text
          </button>
          <button 
            className="px-4 py-2 bg-blue-600 hover:bg-blue-500 text-white flex items-center gap-2 rounded-xl transition-all font-medium text-sm"
          >
            <Mail className="w-4 h-4" /> Email Me This
          </button>
        </div>
      </div>
    </div>
  );
}
